FROM node:20-alpine

WORKDIR /app

# Accept all build args from EasyPanel
ARG NEXT_PUBLIC_APP_URL
ARG NEXT_PUBLIC_SITE_NAME
ARG RESEND_API_KEY
ARG RESEND_FROM_EMAIL
ARG RESEND_TO_EMAIL
ARG PORT
ARG HOSTNAME
ARG NODE_ENV
ARG GIT_SHA

ENV NEXT_PUBLIC_APP_URL=$NEXT_PUBLIC_APP_URL
ENV NEXT_PUBLIC_SITE_NAME=$NEXT_PUBLIC_SITE_NAME

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

EXPOSE 3000
CMD ["npm", "start"]
